     ---------------------------- Error(2019-01-09 15:07:02.7496) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.Data.Entity.Core.EntityCommandExecutionException
      
              Exception Message : An error occurred while executing the command definition. See the inner exception for details.
     
              Inner Exception  : System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> Oracle.ManagedDataAccess.Client.OracleException: ORA-12570: Sesión de Red: error de lectura de paquete inesperado ---> OracleInternal.Network.NetworkException: ORA-12570: Sesión de Red: error de lectura de paquete inesperado ---> System.Net.Sockets.SocketException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
   en System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   en OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   en OracleInternal.TTC.OraBufReader.GetDataFromNetwork()
   en OracleInternal.TTC.OraBufReader.Read(Boolean bIgnoreData)
   en OracleInternal.TTC.MarshallingEngine.UnmarshalUB1(Boolean bIgnoreData)
   en OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Oracle.ManagedDataAccess.Client.OracleException.HandleError(OracleTraceLevel level, OracleTraceTag tag, Exception ex, OracleLogicalTransaction oracleLogicalTransaction)
   en OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   en OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   en Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   en Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   en System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   en System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   en System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   en System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   en System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   en System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   en System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   en System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   en System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   en System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__2[TResult](IEnumerable`1 sequence)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   en System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   en System.Data.Entity.Internal.Linq.InternalSet`1.FindInStore(WrappedEntityKey key, String keyValuesParamName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   en System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   en Proveduria.Repositories.GenericRepository`1.GetById(Object id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Repositories\GenericRepository.cs:línea 37
   en Proveduria.Controllers.ConfiguracionController.GetMedida(Int32 pid) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ConfiguracionController.cs:línea 52 
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12570: Sesión de Red: error de lectura de paquete inesperado ---> OracleInternal.Network.NetworkException (0x80004005): ORA-12570: Sesión de Red: error de lectura de paquete inesperado ---> System.Net.Sockets.SocketException (0x80004005): Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
   en System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   en OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   en OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   en OracleInternal.TTC.OraBufReader.GetDataFromNetwork()
   en OracleInternal.TTC.OraBufReader.Read(Boolean bIgnoreData)
   en OracleInternal.TTC.MarshallingEngine.UnmarshalUB1(Boolean bIgnoreData)
   en OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   en Oracle.ManagedDataAccess.Client.OracleException.HandleError(OracleTraceLevel level, OracleTraceTag tag, Exception ex, OracleLogicalTransaction oracleLogicalTransaction)
   en OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   en OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   en Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   en Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   en System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   en System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   en System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   en System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   en System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior) 
OracleInternal.Network.NetworkException (0x80004005): ORA-12570: Sesión de Red: error de lectura de paquete inesperado ---> System.Net.Sockets.SocketException (0x80004005): Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
   en System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   en OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   en OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   en OracleInternal.TTC.OraBufReader.GetDataFromNetwork()
   en OracleInternal.TTC.OraBufReader.Read(Boolean bIgnoreData)
   en OracleInternal.TTC.MarshallingEngine.UnmarshalUB1(Boolean bIgnoreData)
   en OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired) 
System.Net.Sockets.SocketException (0x80004005): Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
   en System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   en OracleInternal.Network.ReaderStream.Read(OraBuf OB) 
 
              Stack Trace   :    en System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   en System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   en System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   en System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   en System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   en System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   en System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__2[TResult](IEnumerable`1 sequence)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   en System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   en System.Data.Entity.Internal.Linq.InternalSet`1.FindInStore(WrappedEntityKey key, String keyValuesParamName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   en System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   en Proveduria.Repositories.GenericRepository`1.GetById(Object id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Repositories\GenericRepository.cs:línea 37
   en Proveduria.Controllers.ConfiguracionController.GetMedida(Int32 pid) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ConfiguracionController.cs:línea 52
        
              Additional Info  : An error occurred while executing the command definition. See the inner exception for details.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2019-01-09 15:36:47.3140) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.Data.Entity.Validation.DbEntityValidationException
      
              Exception Message : Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
     
              Inner Exception  : System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Proveduria.Repositories.UnitOfWork.Save() en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Repositories\UnitOfWork.cs:línea 202
   en Proveduria.Controllers.ConfiguracionController.GrabarMedida(EPRTA_MEDIDA precord) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ConfiguracionController.cs:línea 91 
 
              Stack Trace   :    en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Proveduria.Repositories.UnitOfWork.Save() en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Repositories\UnitOfWork.cs:línea 202
   en Proveduria.Controllers.ConfiguracionController.GrabarMedida(EPRTA_MEDIDA precord) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ConfiguracionController.cs:línea 91
        
              Additional Info  : Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2019-01-09 15:38:56.3079) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.Data.Entity.Validation.DbEntityValidationException
      
              Exception Message : Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
     
              Inner Exception  : System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Proveduria.Repositories.UnitOfWork.Save() en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Repositories\UnitOfWork.cs:línea 202
   en Proveduria.Controllers.ConfiguracionController.GrabarMedida(EPRTA_MEDIDA precord) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ConfiguracionController.cs:línea 91 
 
              Stack Trace   :    en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Proveduria.Repositories.UnitOfWork.Save() en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Repositories\UnitOfWork.cs:línea 202
   en Proveduria.Controllers.ConfiguracionController.GrabarMedida(EPRTA_MEDIDA precord) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\ConfiguracionController.cs:línea 91
        
              Additional Info  : Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 17:16:40.5563) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Dato Grabado  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 17:17:57.3680) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Dato Grabado  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 17:19:03.7786) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Dato Grabado  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 17:28:22.5135) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Codigo de grupo repetido [CODIGO:08-44]  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 17:32:53.5826) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Codigo de grupo repetido [CODIGO:08-44]  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 17:37:53.6616) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : CCEDILLO : Inicio de Sesion    
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 21:20:28.4452) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : CCEDILLO : Inicio de Sesion    
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 21:22:38.1051) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Dato Grabado  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 21:22:47.2530) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Dato Grabado  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Info(2019-01-09 21:22:56.1269) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : 
      
              Exception Message : 
     
              Inner Exception  : 
 
              Stack Trace   : 
        
              Additional Info  : Dato Grabado  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2019-01-09 22:04:10.2473) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.NullReferenceException
      
              Exception Message : Referencia a objeto no establecida como instancia de un objeto.
     
              Inner Exception  : System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 345 
 
              Stack Trace   :    en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 345
        
              Additional Info  : Referencia a objeto no establecida como instancia de un objeto.  
              -------------------------------------------------------------------
              ----------     
     
     ---------------------------- Error(2019-01-09 22:20:19.4342) --------------------------    
              Machine Name  : CCEDILLO
   
              Exception Type  : System.NullReferenceException
      
              Exception Message : Referencia a objeto no establecida como instancia de un objeto.
     
              Inner Exception  : System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 345 
 
              Stack Trace   :    en Proveduria.Controllers.MovimientoController.Movimiento(Int32 id) en C:\Emapag\Produccion\Proveduria\Proveeduria\Proveeduria\Controllers\MovimientoController.cs:línea 345
        
              Additional Info  : Referencia a objeto no establecida como instancia de un objeto.  
              -------------------------------------------------------------------
              ----------     
     
